/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "abc.check" instead.
 */

#include <check.h>

#include "s21_matrix.h"

START_TEST(test_create_matrix_1) {
  matrix_t A = {0, 0, 0};

  int answer = s21_create_matrix(-1, 3, &A);
  ck_assert_int_eq(answer, ERROR);
}
END_TEST

START_TEST(test_create_matrix_2) {
  matrix_t A = {0, 0, 0};

  int answer = s21_create_matrix(2, -3, &A);
  ck_assert_int_eq(answer, ERROR);
}
END_TEST

START_TEST(test_create_matrix_3) {
  matrix_t A = {0, 0, 0};

  int answer = s21_create_matrix(0, 0, &A);
  ck_assert_int_eq(answer, ERROR);
}
END_TEST

START_TEST(test_create_matrix_4) {
  matrix_t A = {NULL, 0, 0};

  int answer = s21_create_matrix(0, 0, &A);
  ck_assert_int_eq(answer, ERROR);
}
END_TEST

START_TEST(test_create_matrix_5) {
  matrix_t A = {0, 0, 0};

  int answer = s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 2.;
  A.matrix[0][1] = 5.;
  A.matrix[0][2] = 7.;
  A.matrix[1][0] = 6.;
  A.matrix[1][1] = 3.;
  A.matrix[1][2] = 4.;
  A.matrix[2][0] = 5.;
  A.matrix[2][1] = -2.;
  A.matrix[2][2] = -3.;

  ck_assert_int_eq(answer, OK);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(test_create_matrix_6) {
  matrix_t A = {0, 0, 0};

  int answer = s21_create_matrix(1, 1, &A);
  A.matrix[0][0] = 21.2121;

  ck_assert_int_eq(answer, OK);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(test_remove_matrix_1) {
  matrix_t A = {0, 0, 0};

  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 2.;
  A.matrix[0][1] = 5.;
  A.matrix[0][2] = 7.;
  A.matrix[1][0] = 6.;
  A.matrix[1][1] = 3.;
  A.matrix[1][2] = 4.;
  A.matrix[2][0] = 5.;
  A.matrix[2][1] = -2.;
  A.matrix[2][2] = -3.;

  s21_remove_matrix(&A);
  ck_assert_int_eq(A.rows, 0);
  ck_assert_int_eq(A.columns, 0);
}
END_TEST

START_TEST(test_eq_matrix_1) {
  matrix_t A = {0, 0, 0};
  matrix_t B = {0, 0, 0};

  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 2.;
  A.matrix[0][1] = 5.;
  A.matrix[0][2] = 7.;
  A.matrix[1][0] = 6.;
  A.matrix[1][1] = 3.;
  A.matrix[1][2] = 4.;
  A.matrix[2][0] = 5.;
  A.matrix[2][1] = -2.;
  A.matrix[2][2] = -3.;

  s21_create_matrix(3, 3, &B);
  B.matrix[0][0] = 2.;
  B.matrix[0][1] = 5.;
  B.matrix[0][2] = 7.;
  B.matrix[1][0] = 6.;
  B.matrix[1][1] = 3.;
  B.matrix[1][2] = 4.;
  B.matrix[2][0] = 5.;
  B.matrix[2][1] = -2.;
  B.matrix[2][2] = -3.;

  int answer = s21_eq_matrix(&A, &B);
  ck_assert_int_eq(answer, SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(test_eq_matrix_2) {
  matrix_t A = {0, 0, 0};
  matrix_t B = {0, 0, 0};

  s21_create_matrix(2, 3, &A);
  A.matrix[0][0] = 2.;
  A.matrix[0][1] = 5.;
  A.matrix[0][2] = 7.;
  A.matrix[1][0] = 6.;
  A.matrix[1][1] = 3.;
  A.matrix[1][2] = 4.;

  s21_create_matrix(2, 3, &B);
  B.matrix[0][0] = 2.;
  B.matrix[0][1] = 5.;
  B.matrix[0][2] = 7.;
  B.matrix[1][0] = 6.;
  B.matrix[1][1] = 3.;
  B.matrix[1][2] = 4.;

  int answer = s21_eq_matrix(&A, &B);
  ck_assert_int_eq(answer, SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(test_eq_matrix_3) {
  matrix_t A = {0, 0, 0};
  matrix_t B = {0, 0, 0};

  s21_create_matrix(3, 1, &A);
  A.matrix[0][0] = 2.8486459;
  A.matrix[1][0] = 6.9483129;
  A.matrix[2][0] = 5.7412869;

  s21_create_matrix(3, 1, &B);
  B.matrix[0][0] = 2.8486451;
  B.matrix[1][0] = 6.9483121;
  B.matrix[2][0] = 5.7412861;

  int answer = s21_eq_matrix(&A, &B);
  ck_assert_int_eq(answer, FAILURE);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(test_eq_matrix_4) {
  matrix_t A = {0, 0, 0};
  matrix_t B = {0, 0, 0};

  s21_create_matrix(2, 2, &A);
  A.matrix[0][0] = 2.86451;
  A.matrix[0][1] = 4.68465;
  A.matrix[1][0] = 3.98452;
  A.matrix[1][1] = 0.864522;

  s21_create_matrix(2, 2, &B);
  B.matrix[0][0] = 1.86545;
  B.matrix[0][1] = 7.48654;
  B.matrix[1][0] = 2.6845;
  B.matrix[1][1] = 9.453;

  int answer = s21_eq_matrix(&A, &B);
  ck_assert_int_eq(answer, FAILURE);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(test_eq_matrix_5) {
  matrix_t A = {0, 0, 0};
  matrix_t B = {0, 0, 0};

  s21_create_matrix(3, 1, &A);
  A.matrix[0][0] = 2.8486459;
  A.matrix[1][0] = 6.9483129;
  A.matrix[2][0] = 5.7412869;

  s21_create_matrix(3, 1, &B);
  B.matrix[0][0] = 2.848645;
  B.matrix[1][0] = 6.9483129;
  B.matrix[2][0] = 5.7412169;

  int answer = s21_eq_matrix(&A, &B);
  ck_assert_int_eq(answer, FAILURE);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(test_eq_matrix_6) {
  matrix_t A = {0, 0, 0};
  matrix_t B = {0, 0, 0};

  s21_create_matrix(4, 1, &A);
  A.matrix[0][0] = 2.8486459;
  A.matrix[1][0] = 6.9483129;
  A.matrix[2][0] = 5.7412869;
  A.matrix[3][0] = 7.8451;

  s21_create_matrix(3, 1, &B);
  B.matrix[0][0] = 2.848645;
  B.matrix[1][0] = 6.9483129;
  B.matrix[2][0] = 5.7412169;

  int answer = s21_eq_matrix(&A, &B);
  ck_assert_int_eq(answer, FAILURE);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(test_eq_matrix_7) {
  matrix_t A = {0, 0, 0};
  matrix_t B = {0, 0, 0};

  s21_create_matrix(2, 1, &A);
  A.matrix[0][0] = 2.8486459;
  A.matrix[1][0] = 6.9483129;

  s21_create_matrix(2, 3, &B);
  B.matrix[0][0] = 2.848645;
  B.matrix[0][1] = 6.9483129;
  B.matrix[0][2] = 5.7412169;
  B.matrix[1][0] = 5.7869;
  B.matrix[1][1] = 7.8451;
  B.matrix[1][2] = 87.8451;

  int answer = s21_eq_matrix(&A, &B);
  ck_assert_int_eq(answer, FAILURE);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(test_sum_matrix_1) {
  matrix_t A = {0, 0, 0};
  matrix_t B = {0, 0, 0};
  matrix_t C = {0, 0, 0};
  matrix_t ANSWER = {0, 0, 0};

  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 1.;
  A.matrix[0][1] = 2.;
  A.matrix[0][2] = 3.;
  A.matrix[1][0] = 0.;
  A.matrix[1][1] = 4.;
  A.matrix[1][2] = 5.;
  A.matrix[2][0] = 0.;
  A.matrix[2][1] = 0.;
  A.matrix[2][2] = 6.;

  s21_create_matrix(3, 3, &B);
  B.matrix[0][0] = 1.;
  B.matrix[0][1] = 0.;
  B.matrix[0][2] = 0.;
  B.matrix[1][0] = 2.;
  B.matrix[1][1] = 0.;
  B.matrix[1][2] = 0.;
  B.matrix[2][0] = 3.;
  B.matrix[2][1] = 4.;
  B.matrix[2][2] = 1.;

  s21_create_matrix(3, 3, &ANSWER);
  ANSWER.matrix[0][0] = 2.;
  ANSWER.matrix[0][1] = 2.;
  ANSWER.matrix[0][2] = 3.;
  ANSWER.matrix[1][0] = 2.;
  ANSWER.matrix[1][1] = 4.;
  ANSWER.matrix[1][2] = 5.;
  ANSWER.matrix[2][0] = 3.;
  ANSWER.matrix[2][1] = 4.;
  ANSWER.matrix[2][2] = 7.;

  int answer = s21_sum_matrix(&A, &B, &C);
  ck_assert_int_eq(answer, OK);
  ck_assert_int_eq(s21_eq_matrix(&C, &ANSWER), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&C);
  s21_remove_matrix(&ANSWER);
}
END_TEST

START_TEST(test_sum_matrix_2) {
  matrix_t A = {0, 0, 0};
  matrix_t B = {0, 0, 0};
  matrix_t C = {0, 0, 0};
  matrix_t ANSWER = {0, 0, 0};

  s21_create_matrix(2, 2, &A);
  A.matrix[0][0] = 8.4;
  A.matrix[0][1] = 1.5;
  A.matrix[1][0] = 7.7;
  A.matrix[1][1] = 0.4;

  s21_create_matrix(2, 2, &B);
  B.matrix[0][0] = 1.9;
  B.matrix[0][1] = 2.5;
  B.matrix[1][0] = 8.4;
  B.matrix[1][1] = 5.7;

  s21_create_matrix(2, 2, &ANSWER);
  ANSWER.matrix[0][0] = 10.3;
  ANSWER.matrix[0][1] = 4.;
  ANSWER.matrix[1][0] = 16.1;
  ANSWER.matrix[1][1] = 6.1;

  int answer = s21_sum_matrix(&A, &B, &C);
  ck_assert_int_eq(answer, OK);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&C);
  s21_remove_matrix(&ANSWER);
}
END_TEST

START_TEST(test_sum_matrix_3) {
  matrix_t A = {0, 0, 0};
  matrix_t B = {0, 0, 0};
  matrix_t C = {0, 0, 0};
  matrix_t ANSWER = {0, 0, 0};

  s21_create_matrix(1, 1, &A);
  A.matrix[0][0] = 1.878842;

  s21_create_matrix(1, 1, &B);
  B.matrix[0][0] = 5.125485;

  s21_create_matrix(1, 1, &ANSWER);
  ANSWER.matrix[0][0] = 7.004327;

  int answer = s21_sum_matrix(&A, &B, &C);
  ck_assert_int_eq(answer, OK);
  ck_assert_int_eq(s21_eq_matrix(&C, &ANSWER), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&C);
  s21_remove_matrix(&ANSWER);
}
END_TEST

START_TEST(test_sum_matrix_4) {
  matrix_t A = {0, 0, 0};
  matrix_t B = {0, 0, 0};
  matrix_t C = {0, 0, 0};
  matrix_t ANSWER = {0, 0, 0};

  s21_create_matrix(3, 2, &A);
  A.matrix[0][0] = 7.89;
  A.matrix[0][1] = 20.62;
  A.matrix[1][0] = 65.47;
  A.matrix[1][1] = 14.56;
  A.matrix[2][0] = 4.8;
  A.matrix[2][1] = 63.86;

  s21_create_matrix(3, 2, &B);
  B.matrix[0][0] = 9.65;
  B.matrix[0][1] = 89.21;
  B.matrix[1][0] = 23.51;
  B.matrix[1][1] = 74.87;
  B.matrix[2][0] = 34.65;
  B.matrix[2][1] = 41.84;

  s21_create_matrix(3, 2, &ANSWER);
  ANSWER.matrix[0][0] = 17.54;
  ANSWER.matrix[0][1] = 109.83;
  ANSWER.matrix[1][0] = 88.98;
  ANSWER.matrix[1][1] = 89.43;
  ANSWER.matrix[2][0] = 39.45;
  ANSWER.matrix[2][1] = 105.7;

  int answer = s21_sum_matrix(&A, &B, &C);
  ck_assert_int_eq(answer, OK);
  ck_assert_int_eq(s21_eq_matrix(&C, &ANSWER), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&C);
  s21_remove_matrix(&ANSWER);
}
END_TEST

START_TEST(test_sum_matrix_5) {
  matrix_t A = {0, 0, 0};
  matrix_t B = {0, 0, 0};
  matrix_t C = {0, 0, 0};
  matrix_t ANSWER = {0, 0, 0};

  s21_create_matrix(2, 3, &A);
  A.matrix[0][0] = 7.897645;
  A.matrix[0][1] = -2.62452;
  A.matrix[0][2] = 6.476516;
  A.matrix[1][0] = -1.56846;
  A.matrix[1][1] = 4.854174;
  A.matrix[1][2] = -6.86916;

  s21_create_matrix(2, 3, &B);
  B.matrix[0][0] = 9.684520;
  B.matrix[0][1] = -8.21846;
  B.matrix[0][2] = 2.517410;
  B.matrix[1][0] = 7.878742;
  B.matrix[1][1] = 3.657541;
  B.matrix[1][2] = -4.84584;

  s21_create_matrix(2, 3, &ANSWER);
  ANSWER.matrix[0][0] = 17.582165;
  ANSWER.matrix[0][1] = -10.84298;
  ANSWER.matrix[0][2] = 8.993926;
  ANSWER.matrix[1][0] = 6.310282;
  ANSWER.matrix[1][1] = 8.511715;
  ANSWER.matrix[1][2] = -11.715;

  int answer = s21_sum_matrix(&A, &B, &C);
  ck_assert_int_eq(answer, OK);
  ck_assert_int_eq(s21_eq_matrix(&C, &ANSWER), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&C);
  s21_remove_matrix(&ANSWER);
}
END_TEST

START_TEST(test_sum_matrix_6) {
  matrix_t A = {0, 0, 0};
  matrix_t B = {0, 0, 0};
  matrix_t C = {0, 0, 0};

  s21_create_matrix(4, 1, &A);
  A.matrix[0][0] = 2.8486459;
  A.matrix[1][0] = 6.9483129;
  A.matrix[2][0] = 5.7412869;
  A.matrix[3][0] = 7.8451;

  s21_create_matrix(3, 1, &B);
  B.matrix[0][0] = 2.848645;
  B.matrix[1][0] = 6.9483129;
  B.matrix[2][0] = 5.7412169;

  int answer = s21_sum_matrix(&A, &B, &C);
  ck_assert_int_eq(answer, CALCULATION_ERROR);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(test_sum_matrix_7) {
  matrix_t A = {0, 0, 0};
  matrix_t B = {0, 0, 0};
  matrix_t C = {0, 0, 0};

  s21_create_matrix(2, 1, &A);
  A.matrix[0][0] = 2.8486459;
  A.matrix[1][0] = 6.9483129;

  s21_create_matrix(2, 3, &B);
  B.matrix[0][0] = 2.848645;
  B.matrix[0][1] = 6.9483129;
  B.matrix[0][2] = 5.7412169;
  B.matrix[1][0] = 5.7869;
  B.matrix[1][1] = 7.8451;
  B.matrix[1][2] = 87.8451;

  int answer = s21_sum_matrix(&A, &B, &C);
  ck_assert_int_eq(answer, CALCULATION_ERROR);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(test_sum_matrix_8) {
  matrix_t A = {0, 0, 0};
  matrix_t B = {0, 0, 0};
  matrix_t C = {0, 0, 0};

  s21_create_matrix(0, -1, &A);

  s21_create_matrix(2, 3, &B);
  B.matrix[0][0] = 2.848645;
  B.matrix[0][1] = 6.9483129;
  B.matrix[0][2] = 5.7412169;
  B.matrix[1][0] = 5.7869;
  B.matrix[1][1] = 7.8451;
  B.matrix[1][2] = 87.8451;

  int answer = s21_sum_matrix(&A, &B, &C);
  ck_assert_int_eq(answer, ERROR);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(test_sub_matrix_1) {
  matrix_t A = {0, 0, 0};
  matrix_t B = {0, 0, 0};
  matrix_t C = {0, 0, 0};
  matrix_t ANSWER = {0, 0, 0};

  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 1.;
  A.matrix[0][1] = 2.;
  A.matrix[0][2] = 3.;
  A.matrix[1][0] = 0.;
  A.matrix[1][1] = 4.;
  A.matrix[1][2] = 5.;
  A.matrix[2][0] = 0.;
  A.matrix[2][1] = 0.;
  A.matrix[2][2] = 6.;

  s21_create_matrix(3, 3, &B);
  B.matrix[0][0] = 1.;
  B.matrix[0][1] = 0.;
  B.matrix[0][2] = 0.;
  B.matrix[1][0] = 2.;
  B.matrix[1][1] = 0.;
  B.matrix[1][2] = 0.;
  B.matrix[2][0] = 3.;
  B.matrix[2][1] = 4.;
  B.matrix[2][2] = 1.;

  s21_create_matrix(3, 3, &ANSWER);
  ANSWER.matrix[0][0] = 0.;
  ANSWER.matrix[0][1] = 2.;
  ANSWER.matrix[0][2] = 3.;
  ANSWER.matrix[1][0] = -2.;
  ANSWER.matrix[1][1] = 4.;
  ANSWER.matrix[1][2] = 5.;
  ANSWER.matrix[2][0] = -3.;
  ANSWER.matrix[2][1] = -4.;
  ANSWER.matrix[2][2] = 5.;

  int answer = s21_sub_matrix(&A, &B, &C);
  ck_assert_int_eq(answer, OK);
  ck_assert_int_eq(s21_eq_matrix(&C, &ANSWER), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&C);
  s21_remove_matrix(&ANSWER);
}
END_TEST

START_TEST(test_sub_matrix_2) {
  matrix_t A = {0, 0, 0};
  matrix_t B = {0, 0, 0};
  matrix_t C = {0, 0, 0};
  matrix_t ANSWER = {0, 0, 0};

  s21_create_matrix(2, 2, &A);
  A.matrix[0][0] = 8.4;
  A.matrix[0][1] = 1.5;
  A.matrix[1][0] = 7.7;
  A.matrix[1][1] = 0.4;

  s21_create_matrix(2, 2, &B);
  B.matrix[0][0] = 1.9;
  B.matrix[0][1] = 2.5;
  B.matrix[1][0] = 8.4;
  B.matrix[1][1] = 5.7;

  s21_create_matrix(2, 2, &ANSWER);
  ANSWER.matrix[0][0] = 6.5;
  ANSWER.matrix[0][1] = -1.;
  ANSWER.matrix[1][0] = -0.7;
  ANSWER.matrix[1][1] = -5.3;

  int answer = s21_sub_matrix(&A, &B, &C);
  ck_assert_int_eq(answer, OK);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&C);
  s21_remove_matrix(&ANSWER);
}
END_TEST

START_TEST(test_sub_matrix_3) {
  matrix_t A = {0, 0, 0};
  matrix_t B = {0, 0, 0};
  matrix_t C = {0, 0, 0};
  matrix_t ANSWER = {0, 0, 0};

  s21_create_matrix(1, 1, &A);
  A.matrix[0][0] = 1.878842;

  s21_create_matrix(1, 1, &B);
  B.matrix[0][0] = 5.125485;

  s21_create_matrix(1, 1, &ANSWER);
  ANSWER.matrix[0][0] = -3.246643;

  int answer = s21_sub_matrix(&A, &B, &C);
  ck_assert_int_eq(answer, OK);
  ck_assert_int_eq(s21_eq_matrix(&C, &ANSWER), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&C);
  s21_remove_matrix(&ANSWER);
}
END_TEST

START_TEST(test_sub_matrix_4) {
  matrix_t A = {0, 0, 0};
  matrix_t B = {0, 0, 0};
  matrix_t C = {0, 0, 0};
  matrix_t ANSWER = {0, 0, 0};

  s21_create_matrix(3, 2, &A);
  A.matrix[0][0] = 7.89;
  A.matrix[0][1] = 20.62;
  A.matrix[1][0] = 65.47;
  A.matrix[1][1] = 14.56;
  A.matrix[2][0] = 4.8;
  A.matrix[2][1] = 63.86;

  s21_create_matrix(3, 2, &B);
  B.matrix[0][0] = 9.65;
  B.matrix[0][1] = 89.21;
  B.matrix[1][0] = 23.51;
  B.matrix[1][1] = 74.87;
  B.matrix[2][0] = 34.65;
  B.matrix[2][1] = 41.84;

  s21_create_matrix(3, 2, &ANSWER);
  ANSWER.matrix[0][0] = -1.76;
  ANSWER.matrix[0][1] = -68.59;
  ANSWER.matrix[1][0] = 41.96;
  ANSWER.matrix[1][1] = -60.31;
  ANSWER.matrix[2][0] = -29.85;
  ANSWER.matrix[2][1] = 22.02;

  int answer = s21_sub_matrix(&A, &B, &C);
  ck_assert_int_eq(answer, OK);
  ck_assert_int_eq(s21_eq_matrix(&C, &ANSWER), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&C);
  s21_remove_matrix(&ANSWER);
}
END_TEST

START_TEST(test_sub_matrix_5) {
  matrix_t A = {0, 0, 0};
  matrix_t B = {0, 0, 0};
  matrix_t C = {0, 0, 0};
  matrix_t ANSWER = {0, 0, 0};

  s21_create_matrix(2, 3, &A);
  A.matrix[0][0] = 7.897645;
  A.matrix[0][1] = -2.62452;
  A.matrix[0][2] = 6.476516;
  A.matrix[1][0] = -1.56846;
  A.matrix[1][1] = 4.854174;
  A.matrix[1][2] = -6.86916;

  s21_create_matrix(2, 3, &B);
  B.matrix[0][0] = 9.684520;
  B.matrix[0][1] = -8.21846;
  B.matrix[0][2] = 2.517410;
  B.matrix[1][0] = 7.878742;
  B.matrix[1][1] = 3.657541;
  B.matrix[1][2] = -4.84584;

  s21_create_matrix(2, 3, &ANSWER);
  ANSWER.matrix[0][0] = -1.786875;
  ANSWER.matrix[0][1] = 5.59394;
  ANSWER.matrix[0][2] = 3.959106;
  ANSWER.matrix[1][0] = -9.447202;
  ANSWER.matrix[1][1] = 1.196633;
  ANSWER.matrix[1][2] = -2.02332;

  int answer = s21_sub_matrix(&A, &B, &C);
  ck_assert_int_eq(answer, OK);
  ck_assert_int_eq(s21_eq_matrix(&C, &ANSWER), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&C);
  s21_remove_matrix(&ANSWER);
}
END_TEST

START_TEST(test_sub_matrix_6) {
  matrix_t A = {0, 0, 0};
  matrix_t B = {0, 0, 0};
  matrix_t C = {0, 0, 0};

  s21_create_matrix(4, 1, &A);
  A.matrix[0][0] = 2.8486459;
  A.matrix[1][0] = 6.9483129;
  A.matrix[2][0] = 5.7412869;
  A.matrix[3][0] = 7.8451;

  s21_create_matrix(3, 1, &B);
  B.matrix[0][0] = 2.848645;
  B.matrix[1][0] = 6.9483129;
  B.matrix[2][0] = 5.7412169;

  int answer = s21_sub_matrix(&A, &B, &C);
  ck_assert_int_eq(answer, CALCULATION_ERROR);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(test_sub_matrix_7) {
  matrix_t A = {0, 0, 0};
  matrix_t B = {0, 0, 0};
  matrix_t C = {0, 0, 0};

  s21_create_matrix(2, 1, &A);
  A.matrix[0][0] = 2.8486459;
  A.matrix[1][0] = 6.9483129;

  s21_create_matrix(2, 3, &B);
  B.matrix[0][0] = 2.848645;
  B.matrix[0][1] = 6.9483129;
  B.matrix[0][2] = 5.7412169;
  B.matrix[1][0] = 5.7869;
  B.matrix[1][1] = 7.8451;
  B.matrix[1][2] = 87.8451;

  int answer = s21_sub_matrix(&A, &B, &C);
  ck_assert_int_eq(answer, CALCULATION_ERROR);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(test_sub_matrix_8) {
  matrix_t A = {0, 0, 0};
  matrix_t B = {0, 0, 0};
  matrix_t C = {0, 0, 0};

  s21_create_matrix(2, 1, &A);
  A.matrix[0][0] = 2.8486459;
  A.matrix[1][0] = 6.9483129;

  s21_create_matrix(-5, 3, &B);

  int answer = s21_sub_matrix(&A, &B, &C);
  ck_assert_int_eq(answer, ERROR);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(test_mult_number_1) {
  matrix_t A = {0, 0, 0};
  matrix_t C = {0, 0, 0};
  matrix_t ANSWER = {0, 0, 0};
  double number = 2;

  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 1.;
  A.matrix[0][1] = 2.;
  A.matrix[0][2] = 3.;
  A.matrix[1][0] = 0.;
  A.matrix[1][1] = 4.;
  A.matrix[1][2] = 2.;
  A.matrix[2][0] = 2.;
  A.matrix[2][1] = 3.;
  A.matrix[2][2] = 4.;

  s21_create_matrix(3, 3, &ANSWER);
  ANSWER.matrix[0][0] = 2.;
  ANSWER.matrix[0][1] = 4.;
  ANSWER.matrix[0][2] = 6.;
  ANSWER.matrix[1][0] = 0.;
  ANSWER.matrix[1][1] = 8.;
  ANSWER.matrix[1][2] = 4.;
  ANSWER.matrix[2][0] = 4.;
  ANSWER.matrix[2][1] = 6.;
  ANSWER.matrix[2][2] = 8.;

  int answer = s21_mult_number(&A, number, &C);
  ck_assert_int_eq(answer, OK);
  ck_assert_int_eq(s21_eq_matrix(&C, &ANSWER), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&C);
  s21_remove_matrix(&ANSWER);
}
END_TEST

START_TEST(test_mult_number_2) {
  matrix_t A = {0, 0, 0};
  matrix_t C = {0, 0, 0};
  matrix_t ANSWER = {0, 0, 0};
  double number = 0;

  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 1.;
  A.matrix[0][1] = 2.;
  A.matrix[0][2] = 3.;
  A.matrix[1][0] = 0.;
  A.matrix[1][1] = 4.;
  A.matrix[1][2] = 2.;
  A.matrix[2][0] = 2.;
  A.matrix[2][1] = 3.;
  A.matrix[2][2] = 4.;

  s21_create_matrix(3, 3, &ANSWER);
  ANSWER.matrix[0][0] = 0.;
  ANSWER.matrix[0][1] = 0.;
  ANSWER.matrix[0][2] = 0.;
  ANSWER.matrix[1][0] = 0.;
  ANSWER.matrix[1][1] = 0.;
  ANSWER.matrix[1][2] = 0.;
  ANSWER.matrix[2][0] = 0.;
  ANSWER.matrix[2][1] = 0.;
  ANSWER.matrix[2][2] = 0.;

  int answer = s21_mult_number(&A, number, &C);
  ck_assert_int_eq(answer, OK);
  ck_assert_int_eq(s21_eq_matrix(&C, &ANSWER), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&C);
  s21_remove_matrix(&ANSWER);
}
END_TEST

START_TEST(test_mult_number_3) {
  matrix_t A = {0, 0, 0};
  matrix_t C = {0, 0, 0};
  matrix_t ANSWER = {0, 0, 0};
  double number = -3.14;

  s21_create_matrix(2, 1, &A);
  A.matrix[0][0] = 1.531;
  A.matrix[1][0] = 2.8645;

  s21_create_matrix(2, 1, &ANSWER);
  ANSWER.matrix[0][0] = -4.80734;
  ANSWER.matrix[1][0] = -8.99453;

  int answer = s21_mult_number(&A, number, &C);
  ck_assert_int_eq(answer, OK);
  ck_assert_int_eq(s21_eq_matrix(&C, &ANSWER), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&C);
  s21_remove_matrix(&ANSWER);
}
END_TEST

START_TEST(test_mult_number_4) {
  matrix_t A = {0, 0, 0};
  matrix_t C = {0, 0, 0};
  matrix_t ANSWER = {0, 0, 0};
  double number = 5.68;

  s21_create_matrix(1, 3, &A);
  A.matrix[0][0] = 15.31;
  A.matrix[0][1] = 22.87;
  A.matrix[0][2] = -8.845;

  s21_create_matrix(1, 3, &ANSWER);
  ANSWER.matrix[0][0] = 86.9608;
  ANSWER.matrix[0][1] = 129.9016;
  ANSWER.matrix[0][2] = -50.2396;

  int answer = s21_mult_number(&A, number, &C);
  ck_assert_int_eq(answer, OK);
  ck_assert_int_eq(s21_eq_matrix(&C, &ANSWER), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&C);
  s21_remove_matrix(&ANSWER);
}
END_TEST

START_TEST(test_mult_number_5) {
  matrix_t A = {0, 0, 0};
  matrix_t C = {0, 0, 0};
  double number = 5.68;

  s21_create_matrix(0, 3, &A);

  int answer = s21_mult_number(&A, number, &C);
  ck_assert_int_eq(answer, ERROR);
}
END_TEST

START_TEST(test_mult_matrix_1) {
  matrix_t A = {0, 0, 0};
  matrix_t B = {0, 0, 0};
  matrix_t C = {0, 0, 0};
  matrix_t ANSWER = {0, 0, 0};

  s21_create_matrix(3, 2, &A);
  A.matrix[0][0] = 1.;
  A.matrix[0][1] = 4.;
  A.matrix[1][0] = 2.;
  A.matrix[1][1] = 5.;
  A.matrix[2][0] = 3.;
  A.matrix[2][1] = 6.;

  s21_create_matrix(2, 3, &B);
  B.matrix[0][0] = 1.;
  B.matrix[0][1] = -1.;
  B.matrix[0][2] = 1.;
  B.matrix[1][0] = 2.;
  B.matrix[1][1] = 3.;
  B.matrix[1][2] = 4.;

  s21_create_matrix(3, 3, &ANSWER);
  ANSWER.matrix[0][0] = 9.;
  ANSWER.matrix[0][1] = 11.;
  ANSWER.matrix[0][2] = 17.;
  ANSWER.matrix[1][0] = 12.;
  ANSWER.matrix[1][1] = 13.;
  ANSWER.matrix[1][2] = 22.;
  ANSWER.matrix[2][0] = 15.;
  ANSWER.matrix[2][1] = 15.;
  ANSWER.matrix[2][2] = 27.;

  int answer = s21_mult_matrix(&A, &B, &C);
  ck_assert_int_eq(answer, OK);
  ck_assert_int_eq(s21_eq_matrix(&C, &ANSWER), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&C);
  s21_remove_matrix(&ANSWER);
}
END_TEST

START_TEST(test_mult_matrix_2) {
  matrix_t A = {0, 0, 0};
  matrix_t B = {0, 0, 0};
  matrix_t C = {0, 0, 0};
  matrix_t ANSWER = {0, 0, 0};

  s21_create_matrix(2, 1, &A);
  A.matrix[0][0] = 80.7;
  A.matrix[1][0] = 94.13;

  s21_create_matrix(1, 2, &B);
  B.matrix[0][0] = 0.56;
  B.matrix[0][1] = 0.741;

  s21_create_matrix(2, 2, &ANSWER);
  ANSWER.matrix[0][0] = 45.192;
  ANSWER.matrix[0][1] = 59.7987;
  ANSWER.matrix[1][0] = 52.7128;
  ANSWER.matrix[1][1] = 69.75033;

  int answer = s21_mult_matrix(&A, &B, &C);
  ck_assert_int_eq(answer, OK);
  ck_assert_int_eq(s21_eq_matrix(&C, &ANSWER), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&C);
  s21_remove_matrix(&ANSWER);
}
END_TEST

START_TEST(test_mult_matrix_3) {
  matrix_t A = {0, 0, 0};
  matrix_t B = {0, 0, 0};
  matrix_t C = {0, 0, 0};

  s21_create_matrix(4, 1, &A);
  A.matrix[0][0] = 2.8486459;
  A.matrix[1][0] = 6.9483129;
  A.matrix[2][0] = 5.7412869;
  A.matrix[3][0] = 7.8451;

  s21_create_matrix(3, 1, &B);
  B.matrix[0][0] = 2.848645;
  B.matrix[1][0] = 6.9483129;
  B.matrix[2][0] = 5.7412169;

  int answer = s21_mult_matrix(&A, &B, &C);
  ck_assert_int_eq(answer, CALCULATION_ERROR);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(test_mult_matrix_4) {
  matrix_t A = {0, 0, 0};
  matrix_t B = {0, 0, 0};
  matrix_t C = {0, 0, 0};

  s21_create_matrix(2, 1, &A);
  A.matrix[0][0] = 2.8486459;
  A.matrix[1][0] = 6.9483129;

  s21_create_matrix(2, 3, &B);
  B.matrix[0][0] = 2.848645;
  B.matrix[0][1] = 6.9483129;
  B.matrix[0][2] = 5.7412169;
  B.matrix[1][0] = 5.7869;
  B.matrix[1][1] = 7.8451;
  B.matrix[1][2] = 87.8451;

  int answer = s21_mult_matrix(&A, &B, &C);
  ck_assert_int_eq(answer, CALCULATION_ERROR);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
}
END_TEST

START_TEST(test_mult_matrix_5) {
  matrix_t A = {0, 0, 0};
  matrix_t B = {0, 0, 0};
  matrix_t C = {0, 0, 0};
  matrix_t ANSWER = {0, 0, 0};

  s21_create_matrix(2, 3, &A);
  A.matrix[0][0] = 1.;
  A.matrix[0][1] = -1.;
  A.matrix[0][2] = 1.;
  A.matrix[1][0] = 2.;
  A.matrix[1][1] = 3.;
  A.matrix[1][2] = 4.;

  s21_create_matrix(3, 2, &B);
  B.matrix[0][0] = 1.;
  B.matrix[0][1] = 4.;
  B.matrix[1][0] = 2.;
  B.matrix[1][1] = 5.;
  B.matrix[2][0] = 3.;
  B.matrix[2][1] = 6.;

  s21_create_matrix(2, 2, &ANSWER);
  ANSWER.matrix[0][0] = 2.;
  ANSWER.matrix[0][1] = 5.;
  ANSWER.matrix[1][0] = 20.;
  ANSWER.matrix[1][1] = 47.;

  int answer = s21_mult_matrix(&A, &B, &C);
  ck_assert_int_eq(answer, OK);
  ck_assert_int_eq(s21_eq_matrix(&C, &ANSWER), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&B);
  s21_remove_matrix(&C);
  s21_remove_matrix(&ANSWER);
}
END_TEST

START_TEST(test_mult_matrix_6) {
  matrix_t A = {0, 0, 0};
  matrix_t B = {0, 0, 0};
  matrix_t C = {0, 0, 0};

  s21_create_matrix(2, 3, &A);
  A.matrix[0][0] = 1.;
  A.matrix[0][1] = -1.;
  A.matrix[0][2] = 1.;
  A.matrix[1][0] = 2.;
  A.matrix[1][1] = 3.;
  A.matrix[1][2] = 4.;

  s21_create_matrix(-1, 8, &B);

  int answer = s21_mult_matrix(&A, &B, &C);
  ck_assert_int_eq(answer, ERROR);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(test_transpose_1) {
  matrix_t A = {0, 0, 0};
  matrix_t C = {0, 0, 0};
  matrix_t ANSWER = {0, 0, 0};

  s21_create_matrix(3, 2, &A);
  A.matrix[0][0] = 1.;
  A.matrix[0][1] = 4.;
  A.matrix[1][0] = 2.;
  A.matrix[1][1] = 5.;
  A.matrix[2][0] = 3.;
  A.matrix[2][1] = 6.;

  s21_create_matrix(2, 3, &ANSWER);
  ANSWER.matrix[0][0] = 1.;
  ANSWER.matrix[0][1] = 2.;
  ANSWER.matrix[0][2] = 3.;
  ANSWER.matrix[1][0] = 4.;
  ANSWER.matrix[1][1] = 5.;
  ANSWER.matrix[1][2] = 6.;

  int answer = s21_transpose(&A, &C);
  ck_assert_int_eq(answer, OK);
  ck_assert_int_eq(s21_eq_matrix(&C, &ANSWER), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&C);
  s21_remove_matrix(&ANSWER);
}
END_TEST

START_TEST(test_transpose_2) {
  matrix_t A = {0, 0, 0};
  matrix_t C = {0, 0, 0};
  matrix_t ANSWER = {0, 0, 0};

  s21_create_matrix(2, 3, &A);
  A.matrix[0][0] = 5.87;
  A.matrix[0][1] = 7.21;
  A.matrix[0][2] = 0.87165;
  A.matrix[1][0] = -84.1452;
  A.matrix[1][1] = 9.6384;
  A.matrix[1][2] = 8.1835;

  s21_create_matrix(3, 2, &ANSWER);
  ANSWER.matrix[0][0] = 5.87;
  ANSWER.matrix[0][1] = -84.1452;
  ANSWER.matrix[1][0] = 7.21;
  ANSWER.matrix[1][1] = 9.6384;
  ANSWER.matrix[2][0] = 0.87165;
  ANSWER.matrix[2][1] = 8.1835;

  int answer = s21_transpose(&A, &C);
  ck_assert_int_eq(answer, OK);
  ck_assert_int_eq(s21_eq_matrix(&C, &ANSWER), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&C);
  s21_remove_matrix(&ANSWER);
}
END_TEST

START_TEST(test_transpose_3) {
  matrix_t A = {0, 0, 0};
  matrix_t C = {0, 0, 0};
  matrix_t ANSWER = {0, 0, 0};

  s21_create_matrix(1, 1, &A);
  A.matrix[0][0] = 2.71;

  s21_create_matrix(1, 1, &ANSWER);
  ANSWER.matrix[0][0] = 2.71;

  int answer = s21_transpose(&A, &C);
  ck_assert_int_eq(answer, OK);
  ck_assert_int_eq(s21_eq_matrix(&C, &ANSWER), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&C);
  s21_remove_matrix(&ANSWER);
}
END_TEST

START_TEST(test_transpose_4) {
  matrix_t A = {0, 0, 0};
  matrix_t C = {0, 0, 0};
  matrix_t ANSWER = {0, 0, 0};

  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 2.;
  A.matrix[0][1] = 5.;
  A.matrix[0][2] = 7.;
  A.matrix[1][0] = 6.;
  A.matrix[1][1] = 3.;
  A.matrix[1][2] = 4.;
  A.matrix[2][0] = 5.;
  A.matrix[2][1] = -2.;
  A.matrix[2][2] = -3.;

  s21_create_matrix(3, 3, &ANSWER);
  ANSWER.matrix[0][0] = 2.;
  ANSWER.matrix[0][1] = 6.;
  ANSWER.matrix[0][2] = 5.;
  ANSWER.matrix[1][0] = 5.;
  ANSWER.matrix[1][1] = 3.;
  ANSWER.matrix[1][2] = -2.;
  ANSWER.matrix[2][0] = 7.;
  ANSWER.matrix[2][1] = 4.;
  ANSWER.matrix[2][2] = -3;

  int answer = s21_transpose(&A, &C);
  ck_assert_int_eq(answer, OK);
  ck_assert_int_eq(s21_eq_matrix(&C, &ANSWER), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&C);
  s21_remove_matrix(&ANSWER);
}
END_TEST

START_TEST(test_transpose_5) {
  matrix_t A = {0, 0, 0};
  matrix_t C = {0, 0, 0};
  matrix_t ANSWER = {0, 0, 0};

  s21_create_matrix(1, 3, &A);
  A.matrix[0][0] = 2.;
  A.matrix[0][1] = 5.;
  A.matrix[0][2] = 7.;

  s21_create_matrix(3, 1, &ANSWER);
  ANSWER.matrix[0][0] = 2.;
  ANSWER.matrix[1][0] = 5.;
  ANSWER.matrix[2][0] = 7.;

  int answer = s21_transpose(&A, &C);
  ck_assert_int_eq(answer, OK);
  ck_assert_int_eq(s21_eq_matrix(&C, &ANSWER), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&C);
  s21_remove_matrix(&ANSWER);
}
END_TEST

START_TEST(test_transpose_6) {
  matrix_t A = {0, 0, 0};
  matrix_t C = {0, 0, 0};
  matrix_t ANSWER = {0, 0, 0};

  s21_create_matrix(3, 1, &A);
  A.matrix[0][0] = 2.;
  A.matrix[1][0] = 6.;
  A.matrix[2][0] = 5.;

  s21_create_matrix(1, 3, &ANSWER);
  ANSWER.matrix[0][0] = 2.;
  ANSWER.matrix[0][1] = 6.;
  ANSWER.matrix[0][2] = 5.;

  int answer = s21_transpose(&A, &C);
  ck_assert_int_eq(answer, OK);
  ck_assert_int_eq(s21_eq_matrix(&C, &ANSWER), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&C);
  s21_remove_matrix(&ANSWER);
}
END_TEST

START_TEST(test_transpose_7) {
  matrix_t A = {0, 0, 0};
  matrix_t C = {0, 0, 0};
  matrix_t ANSWER = {0, 0, 0};

  s21_create_matrix(3, 0, &A);

  s21_create_matrix(1, 3, &ANSWER);
  ANSWER.matrix[0][0] = 2.;
  ANSWER.matrix[0][1] = 6.;
  ANSWER.matrix[0][2] = 5.;

  int answer = s21_transpose(&A, &C);
  ck_assert_int_eq(answer, ERROR);
  s21_remove_matrix(&C);
  s21_remove_matrix(&ANSWER);
}
END_TEST

START_TEST(test_calc_complements_1) {
  matrix_t A = {0, 0, 0};
  matrix_t C = {0, 0, 0};
  matrix_t ANSWER = {0, 0, 0};

  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 1.;
  A.matrix[0][1] = 2.;
  A.matrix[0][2] = 3.;
  A.matrix[1][0] = 0.;
  A.matrix[1][1] = 4.;
  A.matrix[1][2] = 2.;
  A.matrix[2][0] = 5.;
  A.matrix[2][1] = 2.;
  A.matrix[2][2] = 1.;

  s21_create_matrix(3, 3, &ANSWER);
  ANSWER.matrix[0][0] = 0.;
  ANSWER.matrix[0][1] = 10.;
  ANSWER.matrix[0][2] = -20.;
  ANSWER.matrix[1][0] = 4.;
  ANSWER.matrix[1][1] = -14.;
  ANSWER.matrix[1][2] = 8.;
  ANSWER.matrix[2][0] = -8.;
  ANSWER.matrix[2][1] = -2.;
  ANSWER.matrix[2][2] = 4;

  int answer = s21_calc_complements(&A, &C);
  ck_assert_int_eq(answer, OK);
  ck_assert_int_eq(s21_eq_matrix(&C, &ANSWER), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&C);
  s21_remove_matrix(&ANSWER);
}
END_TEST

START_TEST(test_calc_complements_2) {
  matrix_t A = {0, 0, 0};
  matrix_t C = {0, 0, 0};

  s21_create_matrix(3, 1, &A);
  A.matrix[0][0] = 2.;
  A.matrix[1][0] = 6.;
  A.matrix[2][0] = 5.;

  int answer = s21_calc_complements(&A, &C);
  ck_assert_int_eq(answer, CALCULATION_ERROR);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(test_calc_complements_3) {
  matrix_t A = {0, 0, 0};
  matrix_t C = {0, 0, 0};

  s21_create_matrix(3, 1, &A);
  A.matrix[0][0] = 2.;
  A.matrix[1][0] = 6.;
  A.matrix[2][0] = 5.;

  int answer = s21_calc_complements(&A, &C);
  ck_assert_int_eq(answer, CALCULATION_ERROR);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(test_calc_complements_4) {
  matrix_t A = {0, 0, 0};
  matrix_t C = {0, 0, 0};

  s21_create_matrix(0, 0, &A);

  int answer = s21_calc_complements(&A, &C);
  ck_assert_int_eq(answer, ERROR);
}
END_TEST

START_TEST(test_determinant_1) {
  matrix_t A = {0, 0, 0};
  double result = 0;

  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 1.;
  A.matrix[0][1] = 2.;
  A.matrix[0][2] = 3.;
  A.matrix[1][0] = 4.;
  A.matrix[1][1] = 5.;
  A.matrix[1][2] = 6.;
  A.matrix[2][0] = 7.;
  A.matrix[2][1] = 8.;
  A.matrix[2][2] = 9.;

  int answer = s21_determinant(&A, &result);
  ck_assert_int_eq(answer, OK);
  ck_assert_double_eq_tol(result, 0., 1e-7);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(test_determinant_2) {
  matrix_t A = {0, 0, 0};
  double result = 0;

  s21_create_matrix(1, 3, &A);
  A.matrix[0][0] = 1.;
  A.matrix[0][1] = 2.;
  A.matrix[0][2] = 3.;

  int answer = s21_determinant(&A, &result);
  ck_assert_int_eq(answer, CALCULATION_ERROR);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(test_determinant_3) {
  matrix_t A = {0, 0, 0};
  double result = 0;

  s21_create_matrix(2, 1, &A);
  A.matrix[0][0] = 1.;
  A.matrix[1][0] = 2.;

  int answer = s21_determinant(&A, &result);
  ck_assert_int_eq(answer, CALCULATION_ERROR);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(test_determinant_4) {
  matrix_t A = {0, 0, 0};
  double result = 0;

  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 9.;
  A.matrix[0][1] = 11.;
  A.matrix[0][2] = 17.;
  A.matrix[1][0] = 12.;
  A.matrix[1][1] = 13.;
  A.matrix[1][2] = 22.;
  A.matrix[2][0] = 15.;
  A.matrix[2][1] = 15.;
  A.matrix[2][2] = 27.;

  int answer = s21_determinant(&A, &result);
  ck_assert_int_eq(answer, OK);
  ck_assert_double_eq_tol(result, 0., 1e-7);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(test_determinant_5) {
  matrix_t A = {0, 0, 0};
  double result = 0;

  s21_create_matrix(4, 4, &A);
  A.matrix[0][0] = 9.98;
  A.matrix[0][1] = -11.94;
  A.matrix[0][2] = 1.50;
  A.matrix[0][3] = 7.84;

  A.matrix[1][0] = 12.36;
  A.matrix[1][1] = -13.84;
  A.matrix[1][2] = 2.12;
  A.matrix[1][3] = 0.;

  A.matrix[2][0] = 0;
  A.matrix[2][1] = 15.45;
  A.matrix[2][2] = 2.65;
  A.matrix[2][3] = 7.54;

  A.matrix[3][0] = 9.21;
  A.matrix[3][1] = -2.21;
  A.matrix[3][2] = -2.13;
  A.matrix[3][3] = -6.65;

  int answer = s21_determinant(&A, &result);
  ck_assert_int_eq(answer, OK);
  ck_assert_double_eq_tol(result, 8161.40478152, 1e-07);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(test_determinant_6) {
  matrix_t A = {0, 0, 0};
  double result = 0;

  s21_create_matrix(1, 1, &A);
  A.matrix[0][0] = 9.98;

  int answer = s21_determinant(&A, &result);
  ck_assert_int_eq(answer, OK);
  ck_assert_double_eq_tol(result, 9.98, 1e-7);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(test_determinant_7) {
  matrix_t A = {0, 0, 0};
  double result = 0;

  s21_create_matrix(0, 1, &A);

  int answer = s21_determinant(&A, &result);
  ck_assert_int_eq(answer, ERROR);
}
END_TEST

START_TEST(test_inverse_matrix_1) {
  matrix_t A = {0, 0, 0};
  matrix_t C = {0, 0, 0};
  matrix_t ANSWER = {0, 0, 0};

  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 2.;
  A.matrix[0][1] = 5.;
  A.matrix[0][2] = 7.;
  A.matrix[1][0] = 6.;
  A.matrix[1][1] = 3.;
  A.matrix[1][2] = 4.;
  A.matrix[2][0] = 5.;
  A.matrix[2][1] = -2.;
  A.matrix[2][2] = -3.;

  s21_create_matrix(3, 3, &ANSWER);
  ANSWER.matrix[0][0] = 1.;
  ANSWER.matrix[0][1] = -1.;
  ANSWER.matrix[0][2] = 1.;
  ANSWER.matrix[1][0] = -38.;
  ANSWER.matrix[1][1] = 41.;
  ANSWER.matrix[1][2] = -34.;
  ANSWER.matrix[2][0] = 27.;
  ANSWER.matrix[2][1] = -29.;
  ANSWER.matrix[2][2] = 24;

  int answer = s21_inverse_matrix(&A, &C);
  ck_assert_int_eq(answer, OK);
  ck_assert_int_eq(s21_eq_matrix(&C, &ANSWER), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&C);
  s21_remove_matrix(&ANSWER);
}
END_TEST

START_TEST(test_inverse_matrix_2) {
  matrix_t A = {0, 0, 0};
  matrix_t C = {0, 0, 0};
  matrix_t ANSWER = {0, 0, 0};

  s21_create_matrix(3, 3, &A);
  A.matrix[0][0] = 2.;
  A.matrix[0][1] = 5.;
  A.matrix[0][2] = 7.;
  A.matrix[1][0] = 6.;
  A.matrix[1][1] = 3.;
  A.matrix[1][2] = 4.;
  A.matrix[2][0] = 5.;
  A.matrix[2][1] = -2.;
  A.matrix[2][2] = -3.;

  s21_create_matrix(3, 3, &ANSWER);
  ANSWER.matrix[0][0] = 1.;
  ANSWER.matrix[0][1] = -1.;
  ANSWER.matrix[0][2] = 1.;
  ANSWER.matrix[1][0] = -38.;
  ANSWER.matrix[1][1] = 41.;
  ANSWER.matrix[1][2] = -34.;
  ANSWER.matrix[2][0] = 27.;
  ANSWER.matrix[2][1] = -29.;
  ANSWER.matrix[2][2] = 24;

  int answer = s21_inverse_matrix(&A, &C);
  ck_assert_int_eq(answer, OK);
  ck_assert_int_eq(s21_eq_matrix(&C, &ANSWER), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&C);
  s21_remove_matrix(&ANSWER);
}
END_TEST

START_TEST(test_inverse_matrix_3) {
  matrix_t A = {0, 0, 0};
  matrix_t C = {0, 0, 0};
  matrix_t ANSWER = {0, 0, 0};

  s21_create_matrix(2, 2, &A);
  A.matrix[0][0] = 38.;
  A.matrix[0][1] = 7.;
  A.matrix[1][0] = 42.;
  A.matrix[1][1] = 8.;

  s21_create_matrix(2, 2, &ANSWER);
  ANSWER.matrix[0][0] = 0.8;
  ANSWER.matrix[0][1] = -0.7;
  ANSWER.matrix[1][0] = -4.2;
  ANSWER.matrix[1][1] = 3.8;

  int answer = s21_inverse_matrix(&A, &C);
  ck_assert_int_eq(answer, OK);
  ck_assert_int_eq(s21_eq_matrix(&C, &ANSWER), SUCCESS);
  s21_remove_matrix(&A);
  s21_remove_matrix(&C);
  s21_remove_matrix(&ANSWER);
}
END_TEST

START_TEST(test_inverse_matrix_4) {
  matrix_t A = {0, 0, 0};
  matrix_t C = {0, 0, 0};

  s21_create_matrix(2, 1, &A);
  A.matrix[0][0] = 1.;
  A.matrix[1][0] = 2.;

  int answer = s21_inverse_matrix(&A, &C);
  ck_assert_int_eq(answer, CALCULATION_ERROR);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(test_inverse_matrix_5) {
  matrix_t A = {0, 0, 0};
  matrix_t C = {0, 0, 0};

  s21_create_matrix(1, 1, &A);
  A.matrix[0][0] = 40.;

  int answer = s21_inverse_matrix(&A, &C);
  ck_assert_int_eq(answer, CALCULATION_ERROR);
  s21_remove_matrix(&A);
}
END_TEST

START_TEST(test_inverse_matrix_6) {
  matrix_t A = {0, 0, 0};
  matrix_t C = {0, 0, 0};

  s21_create_matrix(0, 0, &A);

  int answer = s21_inverse_matrix(&A, &C);
  ck_assert_int_eq(answer, ERROR);
}
END_TEST

Suite *tests_create_and_remove(void) {
  Suite *s = suite_create("create_and_remove_matrix");
  TCase *tc1_1 = tcase_create("matrix");

  tcase_add_test(tc1_1, test_create_matrix_1);
  tcase_add_test(tc1_1, test_create_matrix_2);
  tcase_add_test(tc1_1, test_create_matrix_3);
  tcase_add_test(tc1_1, test_create_matrix_4);
  tcase_add_test(tc1_1, test_create_matrix_5);
  tcase_add_test(tc1_1, test_create_matrix_6);

  tcase_add_test(tc1_1, test_remove_matrix_1);

  suite_add_tcase(s, tc1_1);
  return s;
}

Suite *tests_eq(void) {
  Suite *s = suite_create("eq_matrix");
  TCase *tc1_1 = tcase_create("matrix");

  tcase_add_test(tc1_1, test_eq_matrix_1);
  tcase_add_test(tc1_1, test_eq_matrix_2);
  tcase_add_test(tc1_1, test_eq_matrix_3);
  tcase_add_test(tc1_1, test_eq_matrix_4);
  tcase_add_test(tc1_1, test_eq_matrix_5);
  tcase_add_test(tc1_1, test_eq_matrix_6);
  tcase_add_test(tc1_1, test_eq_matrix_7);

  suite_add_tcase(s, tc1_1);
  return s;
}

Suite *tests_sum(void) {
  Suite *s = suite_create("sum_matrix");
  TCase *tc1_1 = tcase_create("matrix");

  tcase_add_test(tc1_1, test_sum_matrix_1);
  tcase_add_test(tc1_1, test_sum_matrix_2);
  tcase_add_test(tc1_1, test_sum_matrix_3);
  tcase_add_test(tc1_1, test_sum_matrix_4);
  tcase_add_test(tc1_1, test_sum_matrix_5);
  tcase_add_test(tc1_1, test_sum_matrix_6);
  tcase_add_test(tc1_1, test_sum_matrix_7);
  tcase_add_test(tc1_1, test_sum_matrix_8);

  suite_add_tcase(s, tc1_1);
  return s;
}

Suite *tests_sub(void) {
  Suite *s = suite_create("sub_matrix");
  TCase *tc1_1 = tcase_create("matrix");

  tcase_add_test(tc1_1, test_sub_matrix_1);
  tcase_add_test(tc1_1, test_sub_matrix_2);
  tcase_add_test(tc1_1, test_sub_matrix_3);
  tcase_add_test(tc1_1, test_sub_matrix_4);
  tcase_add_test(tc1_1, test_sub_matrix_5);
  tcase_add_test(tc1_1, test_sub_matrix_6);
  tcase_add_test(tc1_1, test_sub_matrix_7);
  tcase_add_test(tc1_1, test_sub_matrix_8);

  suite_add_tcase(s, tc1_1);
  return s;
}

Suite *tests_mult_number(void) {
  Suite *s = suite_create("mult_number_matrix");
  TCase *tc1_1 = tcase_create("matrix");

  tcase_add_test(tc1_1, test_mult_number_1);
  tcase_add_test(tc1_1, test_mult_number_2);
  tcase_add_test(tc1_1, test_mult_number_3);
  tcase_add_test(tc1_1, test_mult_number_4);
  tcase_add_test(tc1_1, test_mult_number_5);

  suite_add_tcase(s, tc1_1);
  return s;
}

Suite *tests_mult_matrix(void) {
  Suite *s = suite_create("mult_matrix");
  TCase *tc1_1 = tcase_create("matrix");

  tcase_add_test(tc1_1, test_mult_matrix_1);
  tcase_add_test(tc1_1, test_mult_matrix_2);
  tcase_add_test(tc1_1, test_mult_matrix_3);
  tcase_add_test(tc1_1, test_mult_matrix_4);
  tcase_add_test(tc1_1, test_mult_matrix_5);
  tcase_add_test(tc1_1, test_mult_matrix_6);

  suite_add_tcase(s, tc1_1);
  return s;
}

Suite *tests_transpose(void) {
  Suite *s = suite_create("transpose_matrix");
  TCase *tc1_1 = tcase_create("matrix");

  tcase_add_test(tc1_1, test_transpose_1);
  tcase_add_test(tc1_1, test_transpose_2);
  tcase_add_test(tc1_1, test_transpose_3);
  tcase_add_test(tc1_1, test_transpose_4);
  tcase_add_test(tc1_1, test_transpose_5);
  tcase_add_test(tc1_1, test_transpose_6);
  tcase_add_test(tc1_1, test_transpose_7);

  suite_add_tcase(s, tc1_1);
  return s;
}

Suite *tests_calc_compiments(void) {
  Suite *s = suite_create("calc_compiments_matrix");
  TCase *tc1_1 = tcase_create("matrix");

  tcase_add_test(tc1_1, test_calc_complements_1);
  tcase_add_test(tc1_1, test_calc_complements_2);
  tcase_add_test(tc1_1, test_calc_complements_3);
  tcase_add_test(tc1_1, test_calc_complements_4);

  suite_add_tcase(s, tc1_1);
  return s;
}

Suite *tests_determinant(void) {
  Suite *s = suite_create("determinant_matrix");
  TCase *tc1_1 = tcase_create("matrix");

  tcase_add_test(tc1_1, test_determinant_1);
  tcase_add_test(tc1_1, test_determinant_2);
  tcase_add_test(tc1_1, test_determinant_3);
  tcase_add_test(tc1_1, test_determinant_4);
  tcase_add_test(tc1_1, test_determinant_5);
  tcase_add_test(tc1_1, test_determinant_6);
  tcase_add_test(tc1_1, test_determinant_7);

  suite_add_tcase(s, tc1_1);
  return s;
}

Suite *tests_inverse(void) {
  Suite *s = suite_create("inverse_matrix");
  TCase *tc1_1 = tcase_create("matrix");

  tcase_add_test(tc1_1, test_inverse_matrix_1);
  tcase_add_test(tc1_1, test_inverse_matrix_2);
  tcase_add_test(tc1_1, test_inverse_matrix_3);
  tcase_add_test(tc1_1, test_inverse_matrix_4);
  tcase_add_test(tc1_1, test_inverse_matrix_5);
  tcase_add_test(tc1_1, test_inverse_matrix_6);

  suite_add_tcase(s, tc1_1);
  return s;
}

int main(void) {
  int failed = 0;
  Suite *matrix_tests[] = {tests_create_and_remove(),
                           tests_eq(),
                           tests_sum(),
                           tests_sub(),
                           tests_mult_number(),
                           tests_mult_matrix(),
                           tests_transpose(),
                           tests_calc_compiments(),
                           tests_determinant(),
                           tests_inverse(),
                           NULL};

  for (int i = 0; matrix_tests[i] != NULL; i++) {
    SRunner *sr = srunner_create(matrix_tests[i]);

    srunner_set_fork_status(sr, CK_NOFORK);
    srunner_run_all(sr, CK_NORMAL);

    failed += srunner_ntests_failed(sr);
    srunner_free(sr);
  }

  if (failed == 0) {
    printf("SUCCESS\n");
  } else {
    printf("FAILED\n");
  }

  return failed == 0 ? 0 : 1;
}
